# Generated by Django 4.2.5 on 2023-10-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(null=True, upload_to="photo/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.TextField(default="Угадайте что за фильм?"),
        ),
    ]
